site_name: extendedmode
docs_dir: docs
repo_url: https://github.com/extendedmode/docs-site
theme:
  name: 'readthedocs'
  prev_next_buttons_location: none
  include_homepage_in_sidebar: false
  highlightjs: true
  hljs_languages:
        - lua
  navigation_depth: 2
extra_css:
    - css/extra.css
markdown_extensions:
  - admonition
  - toc:
      permalink: true